apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8080  
  type: LoadBalancer
  #deploys as LB on AWS - default protocol TCP
