name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t bajacloud/springapp:latest -f Dockerfile .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bajacloud/springapp:latest
          format: 'table'
          exit-code: '1'   # fail the pipeline if vulnerabilities are found
          ignore-unfixed: true

      - name: Push Docker image
        run: docker push bajacloud/springapp:latest




  
